"use client";

import { useCallback, useEffect, useRef, useState } from "react";

type Status = "idle" | "connecting" | "connected" | "reconnecting" | "offline";
type Transfer = { name: string; size: number; progress: number; direction: "send" | "receive"; url?: string; type?: string };
type ServerMessage = { type: string; room?: string; text?: string; peerConnected?: boolean; message?: string; sdp?: RTCSessionDescriptionInit; candidate?: RTCIceCandidateInit };
const WS_URL = process.env.NEXT_PUBLIC_WS_URL || "ws://localhost:8080";
const CHUNK = 64 * 1024;
const MAX_FILE = 500 * 1024 * 1024;

export default function Home() {
  const [status,setStatus]=useState<Status>("idle"), [room,setRoom]=useState(""), [roomInput,setRoomInput]=useState(""), [draft,setDraft]=useState(""), [received,setReceived]=useState(""), [peerConnected,setPeerConnected]=useState(false), [error,setError]=useState(""), [copied,setCopied]=useState(false), [transfer,setTransfer]=useState<Transfer|null>(null), [rtcReady,setRtcReady]=useState(false), [toast,setToast]=useState("");
  const socketRef=useRef<WebSocket|null>(null), desiredAction=useRef<{type:"create"|"join";room?:string}|null>(null), reconnectTimer=useRef<ReturnType<typeof setTimeout>|null>(null), intentionalClose=useRef(false), pcRef=useRef<RTCPeerConnection|null>(null), channelRef=useRef<RTCDataChannel|null>(null), incoming=useRef<{meta?:any;chunks:ArrayBuffer[];received:number}>({chunks:[],received:0}), fileInput=useRef<HTMLInputElement|null>(null);

  const notify=useCallback((body:string)=>{setToast(body);setTimeout(()=>setToast(""),2600);if(document.hidden&&"Notification" in window&&Notification.permission==="granted")new Notification("Dera Share",{body});if("vibrate" in navigator)navigator.vibrate(80)},[]);
  const sendSignal=(data:object)=>{if(socketRef.current?.readyState===WebSocket.OPEN)socketRef.current.send(JSON.stringify(data))};
  const bindChannel=useCallback((ch:RTCDataChannel)=>{channelRef.current=ch;ch.binaryType="arraybuffer";ch.onopen=()=>setRtcReady(true);ch.onclose=()=>setRtcReady(false);ch.onmessage=(e)=>{
    if(typeof e.data==="string"){const msg=JSON.parse(e.data);if(msg.kind==="file-meta"){incoming.current={meta:msg,chunks:[],received:0};setTransfer({name:msg.name,size:msg.size,progress:0,direction:"receive",type:msg.fileType});}if(msg.kind==="file-end"){const i=incoming.current;if(!i.meta)return;const blob=new Blob(i.chunks,{type:i.meta.fileType||"application/octet-stream"});const url=URL.createObjectURL(blob);setTransfer({name:i.meta.name,size:i.meta.size,progress:100,direction:"receive",url,type:i.meta.fileType});notify(`${i.meta.name} received`);}}else{const i=incoming.current;i.chunks.push(e.data);i.received+=e.data.byteLength;if(i.meta)setTransfer({name:i.meta.name,size:i.meta.size,progress:Math.min(99,Math.round(i.received/i.meta.size*100)),direction:"receive",type:i.meta.fileType});}
  }},[notify]);
  const makePeer=useCallback(()=>{pcRef.current?.close();const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"}]});pcRef.current=pc;pc.onicecandidate=e=>{if(e.candidate)sendSignal({type:"rtc-ice",candidate:e.candidate.toJSON()})};pc.ondatachannel=e=>bindChannel(e.channel);pc.onconnectionstatechange=()=>{if(["failed","disconnected","closed"].includes(pc.connectionState))setRtcReady(false)};return pc},[bindChannel]);
  const startOffer=useCallback(async()=>{const pc=makePeer();const ch=pc.createDataChannel("files",{ordered:true});bindChannel(ch);const offer=await pc.createOffer();await pc.setLocalDescription(offer);sendSignal({type:"rtc-offer",sdp:offer})},[bindChannel,makePeer]);

  const connect=useCallback((action:{type:"create"|"join";room?:string},reconnect=false)=>{if(socketRef.current&&socketRef.current.readyState<=WebSocket.OPEN)socketRef.current.close();desiredAction.current=action;intentionalClose.current=false;setError("");setStatus(reconnect?"reconnecting":"connecting");const socket=new WebSocket(WS_URL);socketRef.current=socket;socket.onopen=()=>socket.send(JSON.stringify(action));socket.onmessage=async event=>{let data:ServerMessage;try{data=JSON.parse(event.data)}catch{return}if(data.type==="created"&&data.room){setRoom(data.room);setRoomInput(data.room);setStatus("connected");desiredAction.current={type:"join",room:data.room}}else if(data.type==="joined"&&data.room){setRoom(data.room);setRoomInput(data.room);setStatus("connected");setPeerConnected(Boolean(data.peerConnected));if(typeof data.text==="string")setReceived(data.text);desiredAction.current={type:"join",room:data.room};if(data.peerConnected)setTimeout(()=>startOffer(),300)}else if(data.type==="peer"){setPeerConnected(Boolean(data.peerConnected??(data as any).connected));if((data as any).connected)setTimeout(()=>startOffer(),300);else{setRtcReady(false);pcRef.current?.close()}}else if(data.type==="text"&&typeof data.text==="string"){setReceived(data.text);notify("New text received")}else if(data.type==="rtc-offer"&&data.sdp){const pc=makePeer();await pc.setRemoteDescription(data.sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);sendSignal({type:"rtc-answer",sdp:answer})}else if(data.type==="rtc-answer"&&data.sdp&&pcRef.current){await pcRef.current.setRemoteDescription(data.sdp)}else if(data.type==="rtc-ice"&&data.candidate&&pcRef.current){try{await pcRef.current.addIceCandidate(data.candidate)}catch{}}else if(data.type==="error"){setError(data.message||"Something went wrong.");setStatus("idle");intentionalClose.current=true;socket.close()}};socket.onclose=()=>{if(intentionalClose.current)return;setPeerConnected(false);setRtcReady(false);if(desiredAction.current?.room){setStatus("reconnecting");reconnectTimer.current=setTimeout(()=>connect(desiredAction.current!,true),1800)}else setStatus("offline")};socket.onerror=()=>setError("Could not reach the Dera Share server.")},[makePeer,notify,startOffer]);

  useEffect(()=>()=>{intentionalClose.current=true;if(reconnectTimer.current)clearTimeout(reconnectTimer.current);socketRef.current?.close();pcRef.current?.close();if(transfer?.url)URL.revokeObjectURL(transfer.url)},[transfer?.url]);
  const createRoom=()=>connect({type:"create"}); const joinRoom=()=>{const code=roomInput.replace(/\D/g,"").slice(0,6);if(code.length!==6){setError("Enter a 6-digit room code.");return}connect({type:"join",room:code})};
  const sendText=()=>{if(!draft.trim()||socketRef.current?.readyState!==WebSocket.OPEN)return;sendSignal({type:"text",text:draft});setDraft("");notify("Text sent")};
  async function paste(){try{setDraft(await navigator.clipboard.readText())}catch{setError("Clipboard permission was blocked. Paste manually.")}} async function copy(){if(!received)return;try{await navigator.clipboard.writeText(received);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{setError("Could not copy automatically.")}}
  async function enableNotifications(){if("Notification" in window){const p=await Notification.requestPermission();notify(p==="granted"?"Notifications enabled":"Notifications were not enabled")}}
  async function sendFile(file:File){const ch=channelRef.current;if(!ch||ch.readyState!=="open"){setError("File channel is not ready yet. Keep both devices connected for a moment.");return}if(file.size>MAX_FILE){setError("Files are limited to 500 MB in this version.");return}setError("");setTransfer({name:file.name,size:file.size,progress:0,direction:"send",type:file.type});ch.send(JSON.stringify({kind:"file-meta",name:file.name,size:file.size,fileType:file.type}));let offset=0;while(offset<file.size){while(ch.bufferedAmount>4*1024*1024)await new Promise(r=>setTimeout(r,40));const buf=await file.slice(offset,offset+CHUNK).arrayBuffer();ch.send(buf);offset+=buf.byteLength;setTransfer({name:file.name,size:file.size,progress:Math.round(offset/file.size*100),direction:"send",type:file.type})}ch.send(JSON.stringify({kind:"file-end"}));notify(`${file.name} sent`)}
  function leave(){intentionalClose.current=true;if(reconnectTimer.current)clearTimeout(reconnectTimer.current);socketRef.current?.close();pcRef.current?.close();socketRef.current=null;desiredAction.current=null;setRoom("");setRoomInput("");setReceived("");setPeerConnected(false);setRtcReady(false);setTransfer(null);setStatus("idle");setError("")}
  const fmt=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
  return <main className="shell"><section className="card"><header><div className="mark">D</div><div><h1>Dera Share</h1><p>Text and files, directly between your devices.</p></div>{"Notification" in globalThis&&<button className="notifyBtn" onClick={enableNotifications}>Notifications</button>}</header>
  {!room?<div className="setup"><button className="primary big" onClick={createRoom} disabled={status==="connecting"}>{status==="connecting"?"Connecting…":"Create a room"}</button><div className="divider"><span>or join an existing room</span></div><label>6-digit room code</label><div className="joinRow"><input className="codeInput" inputMode="numeric" maxLength={6} value={roomInput} onChange={e=>setRoomInput(e.target.value.replace(/\D/g,""))} onKeyDown={e=>e.key==="Enter"&&joinRoom()} placeholder="000000"/><button className="secondary" onClick={joinRoom}>Join</button></div></div>:
  <div className="workspace"><div className="roomBar"><div><span className={`dot ${status}`}/><strong>{status==="connected"?"Connected":status==="reconnecting"?"Reconnecting…":"Connecting…"}</strong><small>{peerConnected?(rtcReady?"Device linked · Files ready":"Device linked · Preparing files…"):"Waiting for the other device"}</small></div><button className="leave" onClick={leave}>Leave</button></div><div className="roomCode"><span>Room</span><strong>{room}</strong><button onClick={()=>navigator.clipboard.writeText(room)}>Copy code</button></div>
  <div className="tabsTitle">SHARE TEXT</div><div className="editor"><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Paste or type something…" maxLength={50000}/><div className="editorActions"><button onClick={paste}>Paste</button><span>{draft.length.toLocaleString()} / 50,000</span></div></div><button className="primary send" disabled={!draft.trim()||status!=="connected"} onClick={sendText}>Send text</button>
  <div className="fileZone" onClick={()=>fileInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)sendFile(f)}}><input ref={fileInput} hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)sendFile(f);e.currentTarget.value=""}}/><div className="fileIcon">↑</div><strong>{rtcReady?"Send a file":"File sharing is preparing…"}</strong><span>Tap to choose · or drop a file here · up to 500 MB</span></div>
  {transfer&&<div className="transfer"><div><strong>{transfer.direction==="send"?"Sending":"Received"}: {transfer.name}</strong><span>{fmt(transfer.size)} · {transfer.progress}%</span></div><div className="progress"><i style={{width:`${transfer.progress}%`}}/></div>{transfer.url&&<a href={transfer.url} download={transfer.name}>Download</a>}</div>}
  <div className="receivedHead"><label>Latest text</label><span>{received?"Received from your device":"Nothing received yet"}</span></div><div className={`received ${!received?"empty":""}`}><pre>{received||"Incoming text will appear here."}</pre>{received&&<button className="copy" onClick={copy}>{copied?"Copied":"Copy"}</button>}</div></div>}
  {error&&<div className="error" role="alert">{error}</div>}{toast&&<div className="toast">{toast}</div>}<footer>Peer-to-peer files · Temporary rooms · No permanent storage</footer></section></main>;
}
